### ISSUE TITLE
workflow run failed

### ISSUE THREAD

**Issue by qiling-online** [Devilstore/Gladoscheckin#7]
Since Dec. 5, my workflow’s been failing. Looks like the returned data format has changed.
`Run python checkin.py
  python checkin.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
    SENDKEY: 
    COOKIES: ***
Traceback (most recent call last):
  File "checkin.py", line 54, in <module>
    leftdays = int(float(result['data']['leftDays']))
KeyError: 'data'
Error: Process completed with exit code 1.`

**Comment by Devilstore** [comment]
我自己用的没什么问题呀？

**Comment by shihx2003** [comment]
我也是这个问题，请问您解决了吗

**Comment by Devilstore** [comment]
我的是这样的，没问题呀
![1734617093771](https://github.com/user-attachments/assets/38c0b1e6-504c-4335-af50-2c8e17039219)

**Comment by shihx2003** [comment]
![image](https://github.com/user-attachments/assets/91386753-60ce-47eb-aecf-8e73343b9380)
我的是这样的，前几天就报错了，我更新了cookie还是这样

**Comment by Devilstore** [comment]
这里是由于没有指定 pushkey 导致的哦

**Comment by Devilstore** [comment]
> ![image](https://private-user-images.githubusercontent.com/65456616/397413098-91386753-60ce-47eb-aecf-8e73343b9380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTkxOTcsIm5iZiI6MTczNDYxODg5NywicGF0aCI6Ii82NTQ1NjYxNi8zOTc0MTMwOTgtOTEzODY3NTMtNjBjZS00N2ViLWFlY2YtOGU3MzM0M2I5MzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE0MzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNDg0ODM1M2MzOWQwMjlmZmNkYzU3MGY4ZDQxZWI5YmY4NmQ2MjYwZDBlNzJlODU5ZTk4MGFmYmQyOWI0MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V9X6sNSBaPjz_SNe852GHWttkYEFVXiyyI6g3LnE8CE) 我的是这样的，前几天就报错了，我更新了cookie还是这样

修了， 如果需要推送，则需要设置  pushdeer 的 key，设置方法可以看一下 readme.md，

**Comment by qiling-online** [comment]
我重新同步了仓库，并且重新设置了 COOKIES ,还是得到了错误，我并没有设置推送
`Checkin Repeats! Please Try Tomorrow
Send Content:
 账号: **********, P: 0, 剩余: ***** | 
Traceback (most recent call last):
  File "checkin.py", line 90, in <module>
    pushdeer.send_text(title, desp=context)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pypushdeer/pypushdeer.py", line 51, in send_text
    return self._push(text=text, desp=desp, server=server, pushkey=pushkey, text_type='text')
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pypushdeer/pypushdeer.py", line 21, in _push
    raise ValueError("pushkey must be specified")
ValueError: pushkey must be specified
Error: Process completed with exit code 1.`

**Comment by shihx2003** [comment]
> 我重新同步了仓库，并且重新设置了 COOKIES ,还是得到了错误，我并没有设置推送 `Checkin Repeats! Please Try Tomorrow Send Content: 账号: **********, P: 0, 剩余: ***** | Traceback (most recent call last): File "checkin.py", line 90, in <module> pushdeer.send_text(title, desp=context) File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pypushdeer/pypushdeer.py", line 51, in send_text return self._push(text=text, desp=desp, server=server, pushkey=pushkey, text_type='text') File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pypushdeer/pypushdeer.py", line 21, in _push raise ValueError("pushkey must be specified") ValueError: pushkey must be specified Error: Process completed with exit code 1.`



你可以试试按照下面的方法重新设置一下推送，我之前用的石pushplus，前几天发现不能使用了，按照作者的方法改为pushdeer之后就没问题了
![image](https://github.com/user-attachments/assets/ea28cbae-7366-4384-b80a-3ac04445e69a)
注意删除Repository secrets，只保留下面两个
![image](https://github.com/user-attachments/assets/b9f00171-1edf-4679-bb83-c657117d375e)
